### ISSUE TITLE
Fix and normalize flow_autoconfig.sh scripts

### ISSUE THREAD

**Issue by tysonkaufmann** [MetPX/sr_insects#1]
Currently 3 identical flow_autoconfig.sh scripts exist in:

- sr_insects/flakey_broker/flow_autoconfig.sh
- sr_insects/static_flow/flow_autoconfig.sh
- sr_insects/dynamic_flow/flow_autoconfig.sh

The script is missing 2 dependencies for testing: openssh-server and net-tools

Given that this is a config file for setting up a testing environment, the script should not be responsible for installing sarracenia, which it currently does (pip3 install -e ..). This should be decoupled from the flow setup.

I would like to merge all 3 scripts into one located in the root directory and update the dependencies.

**Comment by petersilva** [comment]
yeah that makes sense.

**Comment by tysonkaufmann** [comment]
Scripts have been fixed and merged into one.
